version: '3'

services:
  frontend:
    container_name: 'twoge'
    build: .
    ports:
      - "8080:80"
    networks:
    - twoge-network
    depends_on:
      database:
        condition: service_healthy

  database:
    image: 'postgres'
    container_name: 'twoge-db'
    ports:
      - '5432:5432'
    networks:
    - twoge-network
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    env_file: .env
    healthcheck:
      test: ['CMD', 'pg_isready', '-q', '-d', 'twoge', '-U', 'twoge']
      timeout: 20s
      retries: 10

networks:
  twoge-network:
    driver: bridge

volumes:
  postgres-data: