apiVersion: v1

kind: Secret
metadata:
  name: postgres-secrets
  namespace: steve
type: Opaque
data:
  postgres-password: dHdvZ2U= # twoge
  postgres-user: dHdvZ2U= # twoge
  postgres-database: dHdvZ2U= # twoge