# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: postgres-volume
#   labels:
#     app: twoge
# spec:
#   capacity:
#     storage: 4Gi
#   volumeMode: Filesystem
#   accessModes:
#     - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Retain
#   storageClassName: ""
#   claimRef:
#     namespace: steve
#     name: postgres-claim
#   hostPath:
#     path: /home/steve/data/postgres