apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: postgres-claim
 namespace: steve
spec:
 accessModes:
   - ReadWriteOnce
 volumeMode: Filesystem
 resources:
   requests:
     storage: 4Gi
#  selector: No need for selector when using storage class
#    matchLabels:
#      app: twoge
 storageClassName: "standard" # default storage class in minikube