apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: postgres-claim
spec:
 accessModes:
   - ReadWriteOnce
 volumeMode: Filesystem
 resources:
   requests:
     storage: 4Gi
 selector:
   matchLabels:
     app: twoge