apiVersion: v1

kind: Service
metadata:
  name: twoge-service
  namespace: steve
spec:
  selector:
    app: twoge
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30011