apiVersion: apps/v1
kind: Deployment
metadata:
  name: twoge
  namespace: steve
  labels:
    app: twoge-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: twoge
  template:
    metadata:
      labels:
        app: twoge
    spec:
      containers:
      - name: twoge-frontend
        image: slamoureux/twoge:latest
        env:
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: twoge-config-map
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: DB_PASSWORD
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: twoge-config-map
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: twoge-config-map
              key: DB_PORT
        - name: DB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: twoge-config-map
              key: DB_DATABASE
        ports:
        - containerPort: 80
